# Generated by Django 4.2.2 on 2023-06-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Enter Name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Enter Username')),
                ('email', models.CharField(max_length=100, verbose_name='Enter Description')),
                ('file', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
